### PR TITLE
Fix parsing errors for complex Elm structures

### LINKED ISSUE #1: Parser fails on complex Elm structures with collection constructors and escaped quotes
## Description

The backend debugger crashes when trying to parse Debug.toString output from complex Elm backend models.

## Steps to Reproduce

1. Set up the backend debugger with a Lamdera app
2. Have a backend model that contains:
   - Collections using `SeqDict.fromList`, `Set.fromList`, etc.
   - Strings with escaped quotes, e.g., `"Some text with \"quoted\" content"`
3. Send data from the app to the debugger

## Expected Behavior

The debugger should display the backend model structure, even if it can't parse every detail perfectly.

## Actual Behavior

The parser fails with errors like:
```
Parse error: 
Expecting ',' at row:1 col:334
Expecting '}' at row:1 col:334
```

## Root Causes

1. The parser expects type constructors like `SeqDict` but gets function calls like `SeqDict.fromList`
2. Escaped quotes inside strings break the string parsing logic

### PR DESCRIPTION
**Pull request by CharlonTank**
Fixes #1

## Changes

Added minimal preprocessing in RPC.elm:

1. **Replaces escaped quotes with single quotes**: `\\\"` → `'`
   - Prevents string boundary parsing errors when strings contain quotes
   
2. **Adds graceful error handling**
   - When parsing fails, displays the parse error along with the original text instead of crashing
   - This allows users to see their data even if the parser can't fully process it
   - Improves error messages to include the received JSON for debugging

## Note

The DebugParser already supports SeqDict, SeqSet, and other lamdera/containers types. The only issue was the escaped quotes breaking string parsing.

## Testing

Tested with a Lamdera app containing:
- SeqDict/SeqSet collections from lamdera/containers
- Internationalized strings with escaped quotes
- Deeply nested record structures

The debugger now displays all data correctly.

### CODE REVIEW

**Comment by MartinSStewart** [comment]
Thanks for the PR. It's marked as a draft so I guess you're still working on it?

**Comment by CharlonTank** [comment]
Hey you're welcome, actually I wanted to look at a better implementation by modifying the parser directly, what do you think?

**Comment by MartinSStewart** [comment]
That's fine by me!

**Comment by CharlonTank** [comment]
Ready for review :)

File: src/RPC.elm [hunk 1]
```diff
@@ -18,20 +18,44 @@ import Time
...
                     Ok ok ->
                         Json.Decode.succeed (refineElmValue ok.value)
 
                     Err error ->
-                        Json.Decode.fail error
+                        Json.Decode.succeed (Plain (ElmString ("Parse error: " ++ error ++ "\n\nOriginal: " ++ text)))
             )
 
 
+decodeNullableElmValue : Decoder (Maybe ElmValue)
```
Comment (MartinSStewart) [inline src/RPC.elm]: What is the distinction between this and `Json.Decode.nullable decodeElmValue`?

File: src/RPC.elm [hunk 2]
```diff
@@ -18,20 +18,44 @@ import Time
 import Types exposing (BackendModel, BackendMsg(..), DataType(..), DebugSession, Event(..), Init_, SessionName(..), ToFrontend(..), UpdateFromFrontend_, Update_)
 
 
+cleanDebugString : String -> String
+cleanDebugString text =
+    text
+        |> String.replace "\\n" "\n"
+        |> String.replace "\\t" "\t"
+        |> String.replace "\\r" "\u{000D}"
+        |> String.replace "\\\"" "'"
```
Comment (MartinSStewart) [inline src/RPC.elm]: I don't fully understand this. Why convert a double quote into a single quote? Shouldn't it be `String.replace "\\\"" "\""`?

Comment (MartinSStewart) [reply src/RPC.elm]: ~~Oh, or maybe it should be `String.replace "\\"" "\""`?~~

Nvm, it has to be `\\\"` of course

File: src/RPC.elm (hunk 1 above)
Comment (CharlonTank) [reply src/RPC.elm]: Sorry to answer that late, I thought I did already.
Yeah, there is no difference x)
I changed back to `Json.Decode.nullable decodeElmValue`

File: src/RPC.elm (hunk 2 above)
Comment (MartinSStewart) [reply src/RPC.elm]: Uh, I'm still wondering why you are converting `\"` into `'` and not `"` :sweat_smile:

Comment (CharlonTank) [reply src/RPC.elm]: Hi Martin! You're absolutely right! I just fixed it to use `String.replace "\\\"" "\""` as you suggested. Converting to single quotes was wrong, it should preserve the actual quotes.

The fix is now correctly converting escaped quotes `\"` to actual quotes `"`. Thanks for catching that! 😊
